### ISSUE TITLE
Azure function - Azure-iothub module not found

### ISSUE THREAD

**Issue by rnithish** [Azure-Samples/iot-hub-node-ping#2]
I deployed this sample directly from GitHub using the deploy to Azure button.
While, my device is able to connect to my IoTHub and send messages, the Azure function is failing with the following error

Exception while executing function: Functions.iothubpingfunction. mscorlib: One or more errors occurred. Error: Cannot find module 'azure-iothub'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (D:\home\site\wwwroot\iothubpingfunction\index.js:1:76)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17).
My Azure function runtime version is 0.2, and the same behavior persists even if I upgrade to 0.5

**Comment by rnithish** [comment]
Okay, after running npm install from Kudu, this worked...but for a sample do you think you should ask people to restore packages after deploying? 
If so, you should add steps for this in the docs.

Feel free to close this issue!

**Comment by olivierbloch** [comment]
I need to fix this as something has changed in the way the deployment from ARM template works and it is not taking into account the deploy.cmd script at the root of the repo. I'll try and fix this soon.
The workaround consist in manually installing the npm dependencies:
- open the Azure Portal and navigate to your resource groups.
- Find the one created during the ARM template deployment
- Find the Function in the resource group and bring up its blade in the portal
- Click on "Function App settings" at the bottom on the left menu and then click on "Go to kudu"
- In the new window, you will see a debug console. In this console, type the following commands:
  
  ```
  cd site/wwwroot/iothubpingfunction
  npm install
  ```

This should install the necessary npm dependencies and make the function work.
I'll try and fix the deployment script rapidly.
Thanks for filing the issue!

**Comment by olivierbloch** [comment]
I'll keep this one open until I fix the deployment script.

**Comment by rnithish** [comment]
I guess they are trying to fix this from the KuduSync tool over [here?](https://github.com/projectkudu/kudu/issues/2137)

**Comment by olivierbloch** [comment]
This issue has now been fixed
